import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from "next/image";
import Process from "./components/Process";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="w-screen h-screen fixed top-0 left-0 right-0 bottom-0 z-[100] flex items-center justify-center overflow-auto">
          <div className="w-3/5 h-min bg-white rounded-xl drop-shadow p-3 flex flex-col gap-5">
            {/* Banner */}
            <div className="bg-[#242424] rounded-xl relative">
              <Image
                src="/banner.png"
                alt="img banner"
                width={800}
                height={100}
                className="w-full h-full object-fill"
              />
              <h1 className="absolute top-1/2 left-1/2 text-[60px]  font-bebas -translate-y-1/2 bg-gradient-to-r from-white to-gray-400 text-transparent bg-clip-text">
                Support The Team
              </h1>
            </div>

            {/* Process */}
            <Process />

            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
